name: crispr_tracr_rna_env
channels:
  - biobuilds
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - biopython=1.76
  - blast=2.5.0
  - blinker=1.4
  - boost=1.73.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates
  - cachetools=4.1.1
  - certifi=2021.10.8
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - clustalo=1.2.3
  - cryptography=3.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - dill=0.3.3
  - expat=2.2.9
  - fasta=36.3.8e
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gast=0.3.3
  - glib=2.65.0
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - gst-plugins-base
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - hmmer=3.3.2
  - icu=58.2
  - idna=2.10
  - importlib-metadata
  - intarna=2.3.1
  - joblib=0.14.1
  - jpeg=9d
  - keras=2.4.3
  - keras-base=2.4.3
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libboost=1.73.0
  - libcblas=3.8.0
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.3.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxgboost=1.2.0
  - libxml2=2.9.9
  - lz4-c=1.9.3
  - markdown=3.3.3
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - multidict=4.7.6
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.18.1
  - oauthlib=3.1.0
  - openjdk=8.0.152
  - openssl=1.1.1n
  - opt_einsum=3.1.0
  - pandas=1.0.3
  - pcre=8.44
  - perl=5.26.2
  - perl-bioperl
  - perl-biox-seq=0.006007
  - perl-compress-bgzf=0.005
  - perl-file-which=1.23
  - perl-threaded=5.26.0
  - perl-yaml=1.29
  - pip=20.2.2=py_0
  - prodigal=2.6.3=1
  - protobuf=3.13.0.1
  - pthread-stubs=0.4
  - py-boost=1.73.0
  - py-xgboost=1.2.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - regex=2019.03.09
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.3
  - tensorboard=2.3.0
  - tensorboard-plugin-wit
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.3.0
  - termcolor=1.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - urllib3=1.25.11
  - viennarna=2.4.18
  - vmatch=2.3.0
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xgboost=1.2.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.2
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.9
