#folder_genomes = "/media/alex/Elements/data/tracrBenchmarkOtherImplementation_anti_repeat"
#file_crispr_idetify = "test_data/test_identify_summary/Complete_summary.csv"
#folder_temp = "test_data/test_temp/"
#folder_output = "/media/alex/Elements/crispr_tracr_anti_repeats_result"
#output_file_name = "anti_repeat_result_crispr_tracr.csv"

folder_genomes = "/media/alex/Elements/data/tracrBenchmark_10_files"
file_crispr_idetify = "test_data/test_identify_summary/Complete_summary.csv"
folder_temp = "test_data/10_files/"
folder_output = "/media/alex/Elements/crispr_tracr_10_files_result"
output_file_name = "crispr_tracr_10_files.csv"
hmm_model = "tools/cov_matrix/s2_b14/cov_matrix.cm"